version: "3.7"
services: 
 mysql:
  image: mysql:latest
  restart: always
  container_name: Full2020_086399
  volumes:
   - db_data:/var/lib/mysql
  ports:
   - "3306:3306"
  networks:
   Bridge-Zadanie-1:
    ipv4_address: 10.0.10.3
  environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: chmury
      MYSQL_USER: JRadomski
      MYSQL_PASSWORD: 1234
 java:
  image: urcherion/radomskichmura:latest
  stdin_open: true
  container_name: JRadomski
  depends_on:
   - mysql
  links:
   - mysql
  networks:
   - Bridge-Zadanie-1:
      ipv4_address: 10.0.10.4
networks:
 Bridge-Zadanie-1:
  driver: bridge
  ipam:
   config:
    - subnet: 10.0.10.0/24
volumes:
 db_data: {}
